spring:
  cloud:
    gateway:
      routes:

        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: common_route
          uri: http://localhost:8082
          predicates:
            - Path=/email/**


